//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Bookstore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Author
    {
        public Tbl_Author()
        {
            this.Tbl_Product = new HashSet<Tbl_Product>();
        }
    
        public int AuthorId { get; set; }
        public string AuthorName { get; set; }
    
        public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }
    }
}
